### ISSUE TITLE
Panneau de configuration\Tous les éléments du Panneau de configuration\Comptes d’utilisateurs\Gérer les comptes\Modifier un compte

### ISSUE THREAD

**Issue by AvatarWeb1** [MicrosoftDocs/visualstudio-docs.fr-fr#15]
Panneau de configuration\Tous les éléments du Panneau de configuration\Comptes d’utilisateurs\Gérer les comptes\Modifier un compte

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f307022f-0b34-372f-2185-b61227c110a7
* Version Independent ID: feabd94b-8396-4c5c-cbb4-cad94f2a476f
* Content: [Résoudre les problèmes d’installation de Visual Studio 2017](https://docs.microsoft.com/fr-fr/visualstudio/install/troubleshooting-installation-issues)
* Content Source: [docs/install/troubleshooting-installation-issues.md](https://github.com/MicrosoftDocs/visualstudio-docs.fr-fr/blob/live/docs/install/troubleshooting-installation-issues.md)
* Product: **visual-studio-dev15**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by gosali** [comment]
Bonjour, @AvatarWeb1 ,  

Merci pour votre feedback.  

Nous révisons activement vos commentaires et nous vous recontacterons bientôt.  
Pourriez-vous nous fournir plus de détails sur ce problème?

Cordialement,  
L’équipe Microsoft DOCS International

**Comment by gosali** [comment]
Bonjour, @AvatarWeb1 ,

Merci pour votre feedback.

Nous révisons activement vos commentaires et nous vous recontacterons bientôt.
Pourriez-vous nous fournir plus de détails sur ce problème?

Cordialement,
L’équipe Microsoft DOCS International

**Comment by DavidPrio** [comment]
Bonjour, @AvatarWeb1 ,

Merci pour votre feedback.

Nous révisons activement vos commentaires et nous vous recontacterons bientôt.
Pourriez-vous nous fournir plus de détails sur ce problème?
CC @Sara-Nicolini, @nokura
Cordialement,
L’équipe Microsoft DOCS International

**Comment by DavidPrio** [comment]
Bonjour, @AvatarWeb1 ,
Merci de nous avoir fait part de votre opinion. Nous avons besoin de renseignements complémentaires afin de résoudre le problème. Pourriez-vous nous donner des instructions plus détaillées quant aux documents/lignes nécessitant une révison/correction?
Cordialement,
L’équipe Microsoft DOCS International

**Comment by LisandroSu** [comment]
Bonjour, @AvatarWeb1 ,

Merci de nous avoir fait part de votre opinion. Nous avons besoin de renseignements complémentaires afin de résoudre le problème. Pourriez-vous nous donner des instructions plus détaillées quant aux documents/lignes nécessitant une révison/correction?

Cordialement,
L’équipe Microsoft DOCS International

**Comment by LisandroSu** [comment]
Bonjour, @AvatarWeb1 

Nous vous remercions une nouvelle fois pour votre commentaire.

Malheureusement, nous manquons toujours d’informations et nous ne pouvons pas traiter vos commentaires. Nous fermons ce problème GitHub pour l’instant, mais nous vous encourageons à soumettre plus de commentaires à l’avenir.

Cordialement,
L’équipe internationale Microsoft DOCS
