### ISSUE TITLE
Problème de lancement

### ISSUE THREAD

**Issue by clequang** [MicrosoftDocs/visualstudio-docs.fr-fr#57]
En arrivant à l'étape "Exécuter l'application", l'application ne se lance pas. 
Il y a une erreur dans la console Output : 
------ Build started: Project: NodejsWebApp, Configuration: Debug Any CPU ------
		npm ERR! missing script: build
		npm ERR! A complete log of this run can be found in:
		npm ERR!     C:\Users\xxxx\AppData\Roaming\npm-cache\_logs\2019-06-05T22_37_31_702Z-debug.log
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VisualStudio\v16.0\Node.js Tools\Microsoft.NodejsToolsV2.targets(60,5): error MSB3073: The command "npm run build" exited with code 1.
Done building project "NodejsWebApp.njsproj" -- FAILED.

Build FAILED.

Pour résoudre le problème, je suis aller dans le fichier package.json et rajouter la ligne suivante :
  "scripts": {
    "build": "webpack --config webpack-config.js"
  }

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: c4b0ea28-4a31-a3ea-fa5f-c32d5c72d4bd
* Version Independent ID: 31bd064b-51eb-5505-986e-2c7148784085
* Content: [Créer une application Node.js et React - Visual Studio](https://docs.microsoft.com/fr-fr/visualstudio/javascript/tutorial-nodejs-with-react-and-jsx?view=vs-2019#run-the-app)
* Content Source: [docs/javascript/tutorial-nodejs-with-react-and-jsx.md](https://github.com/MicrosoftDocs/visualstudio-docs.fr-fr/blob/live/docs/javascript/tutorial-nodejs-with-react-and-jsx.md)
* Product: **visual-studio-windows**
* Technology: **vs-javascript**
* GitHub Login: @Mikejo5000
* Microsoft Alias: **mikejo**

**Comment by CeciAc** [comment]
Bonjour @clequang 

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
