### ISSUE TITLE
 Environnements Python

### ISSUE THREAD

**Issue by idurand** [MicrosoftDocs/visualstudio-docs.fr-fr#58]
Après avoir installé Anaconda, j'essaie de suivre ce tuto pour obtenir un Python interactif.
Mais je bloque au premier point.

1.Ouvrez Visual Studio, basculez vers la fenêtre Environnements Python (Affichage > Autres fenêtres > Environnements Python), puis sélectionnez un environnement Anaconda.

Car il n'y a pas de choix "Autres fenêtres" dans le menu "Affichage".
Je n' ai pas d' expérience avec vs-code et ne sait comment continuer.
Si quelqu'un pouvait me débloquer...
Merci d'avance

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 506c3122-a80b-1b70-e899-83fac96f4187
* Version Independent ID: c449e3bb-b602-098e-5167-31c3d5e02350
* Content: [IPython REPL (fenêtre interactive) - Visual Studio](https://docs.microsoft.com/fr-fr/visualstudio/python/interactive-repl-ipython?view=vs-2019#feedback)
* Content Source: [docs/python/interactive-repl-ipython.md](https://github.com/MicrosoftDocs/visualstudio-docs.fr-fr/blob/live/docs/python/interactive-repl-ipython.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by CeciAc** [comment]
Bonjour @idurand

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
