### ISSUE TITLE
Code coverage Menu...

### ISSUE THREAD

**Issue by sybaris** [MicrosoftDocs/visualstudio-docs.fr-fr#67]
Hi,

I am using Visual Studio 2019 Enterprise. In the Test menu, I don't have the same menu like in your screenshoot. I have only "Live Unit Testing" and "Windows".
I can find the menu item "Analyze Code Coverage for All Tests" only in Test Explorer window.

Please update the screenshoot and the text to explain where to find this option...

Regards
Jean-Pierre

My menu Test :
![image](https://user-images.githubusercontent.com/11009997/66385959-b2d87180-e9c1-11e9-81cc-f484b1c1f6fd.png)

Where to find the menu  "Analyze Code Coverage for All Tests"
![image](https://user-images.githubusercontent.com/11009997/66385939-a94f0980-e9c1-11e9-9369-d640971ff1ad.png)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 4305ee45-a84a-aa05-5b94-4f9d77dadc40
* Version Independent ID: 47acca13-0363-7ea3-08e3-4f2039705223
* Content: [Tests de couverture du code - Visual Studio](https://docs.microsoft.com/fr-fr/visualstudio/test/using-code-coverage-to-determine-how-much-code-is-being-tested?view=vs-2019)
* Content Source: [docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md](https://github.com/MicrosoftDocs/visualstudio-docs.fr-fr/blob/live/docs/test/using-code-coverage-to-determine-how-much-code-is-being-tested.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-test**
* GitHub Login: @gewarren
* Microsoft Alias: **gewarren**

**Comment by srvbpigh** [comment]
Hello, @sybaris
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @sybaris 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/visualstudio-docs/issues/4076.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
