### ISSUE TITLE
Installation package for a Python website in an IIS environment

### ISSUE THREAD

**Issue by Fox15145** [MicrosoftDocs/visualstudio-docs.fr-fr#72]
Thanks for this usefull page.
Maybe this link will help other people on this topic: 
   • https://github.com/Fox15145/Speed-Starter-Python_Website-Under-IIS 
This is an installation package (in Batch an Powershell) for a Python website in an IIS environment.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ed35685d-e409-d962-c450-7297a1f3c003
* Version Independent ID: 224fab0f-fd26-396f-cdd8-921533d2aeba
* Content: [Configurer des applications web Python pour IIS - Visual Studio](https://docs.microsoft.com/fr-fr/visualstudio/python/configure-web-apps-for-iis-windows?view=vs-2019#feedback)
* Content Source: [docs/python/configure-web-apps-for-iis-windows.md](https://github.com/MicrosoftDocs/visualstudio-docs.fr-fr/blob/live/docs/python/configure-web-apps-for-iis-windows.md)
* Product: **visual-studio-windows**
* Technology: **vs-python**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by srvbpigh** [comment]
Hello, @Fox15145
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Fox15145 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continually improve your experience.

Kind regards,
Microsoft DOCS International Team
