### ISSUE TITLE
Lire les exemples sur la page en anglais pour comprendre leur fonctionnement

### ISSUE THREAD

**Issue by MarcusGambit** [MicrosoftDocs/visualstudio-docs.fr-fr#75]
Les mots dans lesquels sont effectuées les recherches on été traduits en français ce qui fait que l'exemple ne fonctionne plus. 
=&gt; Lire les exemples sur la page en anglais pour comprendre leur fonctionnement.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: b53053a2-c37a-99a8-fdaf-7322de927cf8
* Version Independent ID: 55a43af3-3743-9c8f-bf24-50301db7c37c
* Content: [Utiliser les expressions régulières - Visual Studio](https://docs.microsoft.com/fr-fr/visualstudio/ide/using-regular-expressions-in-visual-studio?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DFR-FR%26k%3Dk(vs.netregularexpressionhelp)%3Bk(TargetFrameworkMoniker-.NETFramework%2CVersion%3Dv4.6.1)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=vs-2017#feedback)
* Content Source: [docs/ide/using-regular-expressions-in-visual-studio.md](https://github.com/MicrosoftDocs/visualstudio-docs.fr-fr/blob/live/docs/ide/using-regular-expressions-in-visual-studio.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-general**
* GitHub Login: @TerryGLee
* Microsoft Alias: **tglee**

**Comment by srvbpigh** [comment]
Hello, @MarcusGambit
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Cher(ère) @MarcusGambit

Merci pour votre contribution.

Les demandes de tirage relatives au contenu traduit automatiquement ne sont actuellement pas acceptées.

Nous apprécions vos contributions et suggestions au contenu issu de la traduction humaine, qui sont utilisées pour effectuer l’apprentissage des moteurs de traduction automatique. Vos contributions amélioreront ainsi la qualité des traductions humaine et machine.

Pour distinguer les rubriques traduites manuellement de celles traduites automatiquement, référez-vous à la valeur de métadonnées ms.translationtype qui figure dans l’en-tête de chaque fichier de contenu : "HT" fait référence à la traduction humaine et "MT" à la traduction machine.

Un grand merci pour votre aide.

L’équipe Microsoft DOCS Global Experience
