### ISSUE TITLE
Renseignment

### ISSUE THREAD

**Issue by Chadoxi** [MicrosoftDocs/visualstudio-docs.fr-fr#80]
Bonjour, j'aimerais savoir car il n'y a pas longtemps, j'ai fait un générateur avec visual studio qui génère des cartes bancaires factices. ma professeur crois que c'était une vraie alors que je voulais juste tester une un site de boutique pour voir leur réponse négative car la carte ne passait pas car je développe un site.
Puis-je savoir si je fais un générateur sans avoir besoin d'internet est légal ?
Merci.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 26fa83b1-ca9d-0800-423b-ce6f4a1668a8
* Version Independent ID: fc5869c5-4d4b-bba3-1c32-caf9d13dfd21
* Content: [Génération de code et modèles de texte T4 - Visual Studio](https://docs.microsoft.com/fr-fr/visualstudio/modeling/code-generation-and-t4-text-templates?view=vs-2019#feedback)
* Content Source: [docs/modeling/code-generation-and-t4-text-templates.md](https://github.com/MicrosoftDocs/visualstudio-docs.fr-fr/blob/live/docs/modeling/code-generation-and-t4-text-templates.md)
* Product: **visual-studio-windows**
* Technology: **vs-ide-modeling**
* GitHub Login: @JoshuaPartlow
* Microsoft Alias: **joshuapa**

**Comment by srvbpigh** [comment]
Hello, @Chadoxi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Bonjour @Chadoxi,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/visualstudio-docs/issues/5341.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International
